### ISSUE TITLE
Add support for trimou

### ISSUE THREAD

**Issue by jreijn** [jreijn/spring-comparing-template-engines#13]
http://trimou.org/doc/latest.html#spring_mvc

**Comment by Vest** [comment]
The issue (how many years old?!) is solved now.
You can download the new version of the repository and test it.

I had to implement a custom View & ViewResolver (stole many parts from Trimou itself), because they don't support Spring 5.

The engine looks interesting, faster than many other engines. If you can retest & update the results, this will be interesting to know.
