### ISSUE TITLE
Add HtmlFlow

### ISSUE THREAD

**Issue by fmcarvalho** [jreijn/spring-comparing-template-engines#34]
[HtmlFlow](https://github.com/xmlet/HtmlFlow)  is a Java DSL to write typesafe HTML documents.  

HtmlFlow is at least two fold faster than the current best template engine in spring-comparing-template-engines.

HtmlFlow is widely used to build dynamic HTML documents, such as papers, reports, emails, etc, involving complex programing tasks which are hardly achieved through textual templates. Moreover, HtmlFlow can also be used as a web template engine allying its performance boost with its HTML strongly type safety characteristics.

**Comment by Vest** [comment]
Thank you for the issue. It is solved. 

Unfortunately, I have to reject your PR #35 for several reasons:
* I have changed the project a lot, so your PR should have been rewritten;
* After I wrote my version (close to yours, thank you for the code once again), I found out that the static **DynamicHtml** doesn't behave well during the concurrent access to the page. The block `<html>` is written two times into the response, and I couldn't find out why. So I have decided to create a method that creates **DynamicHtml** on every request. Regardless this change, I think **HtmlFlow** beats JSP.
* meanwhile, I had to disable caching of views as usual;
* I don't need tests in this project, because I don't know what to test... the body?!
* I had to change your code to use **Bootstrap 4**.
